apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chatt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: chatt-app-backend
          image: deepu001/chat-app-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
