apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  namespace: chatt-app
spec:
   replicas: 1
   selector: 
     matchLabels:
       app: frontend
   template:
     metadata:
       labels: 
        app: frontend
     spec:
       containers:
       - name: chatt-app-frontend
         image: deepu001/chat-app-frontend
         ports:
         - containerPort: 80
         env:
         - name: NODE_ENV
           value: production         